# Generated by Django 2.2.6 on 2019-10-27 13:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0014_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('skills', models.CharField(default=None, max_length=255)),
                ('due_date', models.CharField(default=None, max_length=255)),
                ('added_by', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(default=None, max_length=255)),
                ('sex', models.CharField(default=None, max_length=255)),
                ('dob', models.CharField(default=None, max_length=255)),
                ('access', models.CharField(default=None, max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='logged_email',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='competencies',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_app.User'),
        ),
        migrations.AlterField(
            model_name='measurableresults',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_app.User'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_app.User'),
        ),
    ]
